logging:
  level:
    root: info
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    csrf:
      enabled: true
    config-url: http://localhost:8080/api-docs
    operations-sorter: method
spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    url: jdbc:mysql://localhost:3306/db
    user: mysql
    password: mysql
    #url: jdbc:postgresql://localhost:5432/?currentSchema=public
    #user: postgres
    #password: postgres
    database-change-log-lock-table: liquibase_lock
    database-change-log-table: liquibase
    clear-checksums: false
  datasource:
    url: jdbc:mysql://localhost:3306/db
    password: mysql
    username: mysql
    #url: jdbc:postgresql://localhost:5432/?currentSchema=public
    #password: postgres
    #username: postgres
    hikari:
      # some free cloud services limit number of connections in the free tier
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
telegrambots:
  enabled: false
  apikey: ${TELEGRAM_APIKEY:change-me}
  username: ${TELEGRAM_USERNAME:change-me}
server:
  port: 8080