version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'maria'
      MYSQL_PASSWORD: 'maria'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./maria-data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - '3307'

  # https://mcr.microsoft.com/en-us/product/mssql/server/about
  #sql-server-db:
    #container_name: sql-server-db
    #image: mcr.microsoft.com/mssql/server
    #image: mcr.microsoft.com/mssql/rhel/server:2022-latest
    #ports:
      #- "1433:1433"
    #environment:
      #SA_PASSWORD: "mssqlserver"
      #ACCEPT_EULA: "Y"

